export default {
  startDiscovery: jest.fn(),
  stopDiscovery: jest.fn(),
  startPairing: jest.fn(async () => {}),
  submitPin: jest.fn(async () => true),
  cancelPairing: jest.fn(),
  startAirPlayPairing: jest.fn(async () => {}),
  submitAirPlayPin: jest.fn(async () => true),
  connect: jest.fn(async () => {}),
  disconnect: jest.fn(async () => {}),
  forgetDevice: jest.fn(async () => {}),
  sleep: jest.fn(async () => {}),
  wake: jest.fn(async () => {}),
  setMuted: jest.fn(async () => {}),
  setVolume: jest.fn(async () => {}),
  pressButton: jest.fn(async () => {}),
  holdButton: jest.fn(async () => {}),
  playPause: jest.fn(async () => {}),
  skipBy: jest.fn(async () => {}),
  seekTo: jest.fn(async () => {}),
  touchStart: jest.fn(),
  touchMove: jest.fn(),
  touchEnd: jest.fn(),
  sendText: jest.fn(async () => {}),
  loadApps: jest.fn(async () => {}),
  launchApp: jest.fn(async () => {}),
  getDiagnosticsSnapshot: jest.fn(async () => ({})),
  addListener: jest.fn(),
  removeListeners: jest.fn(),
};
